name: Build with pkg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: sudo npx npm-force-resolutions
    - run: npm install -g pkg
    - run: npm install
    - run: pkg .
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: interestcircle
        path: ./*.exe